export const OPEN_DIARYFORM = 'OPEN_DIARYFORM'
export const CLOSE_DIARYFORM = 'CLOSE_DIARYFORM'

export const CREATE_DIARY = 'CREATE_DIARY'
export const DELETE_DIARY = 'DELETE_DIARY'
export const UPDATE_DIARY = 'UPDATE_DIARY'
export const DELETE_ALL_DIARIES = 'DELETE_ALL_DIARIES'

export const OPEN_ALERT = 'OPEN_ALERT'
export const CLOSE_ALERT= 'CLOSE_ALERT'